/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Admin;

import static Admin.Cpm.server;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author john
 */
public final class cpmresult extends javax.swing.JFrame {
static final String server = "jdbc:mysql://localhost/cpm";
    public String card_number = "";
        byte[] rimage = null;
    private static int reqID = 0;
    private static int cardNo = 0;
    private PreparedStatement addpat, idp, labres = null;
    private PreparedStatement addpay = null;
    
    ResultSet rs = null;
    Connection con = null;
    Statement sql = null;
    ResultSet labrs;
    /**
     * Creates new form cpmresult
     */
    public cpmresult() {
        initComponents();
         
         DBConnect();
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ind26 = new javax.swing.JPanel();
        ind27 = new javax.swing.JPanel();
        btnlabsave = new javax.swing.JLabel();
        jLabel74 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        notes = new javax.swing.JTextArea();
        jLabel75 = new javax.swing.JLabel();
        ind54 = new javax.swing.JPanel();
        jLabel72 = new javax.swing.JLabel();
        btnlabsearch = new javax.swing.JLabel();
        jLabel73 = new javax.swing.JLabel();
        jLabel78 = new javax.swing.JLabel();
        ind53 = new javax.swing.JPanel();
        ind25 = new javax.swing.JPanel();
        jLabel76 = new javax.swing.JLabel();
        jLabel77 = new javax.swing.JLabel();
        ind51 = new javax.swing.JPanel();
        jtxtlabgender = new javax.swing.JTextField();
        jLabel86 = new javax.swing.JLabel();
        ind36 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jtxtlabdoctor = new javax.swing.JTextField();
        Eosinophil = new javax.swing.JTextField();
        wbc = new javax.swing.JTextField();
        ind29 = new javax.swing.JPanel();
        ind45 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        ind30 = new javax.swing.JPanel();
        ind46 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        ind31 = new javax.swing.JPanel();
        Monocyte = new javax.swing.JTextField();
        ind33 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        ind34 = new javax.swing.JPanel();
        Lymphocyte = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        ind32 = new javax.swing.JPanel();
        ind35 = new javax.swing.JPanel();
        ind52 = new javax.swing.JPanel();
        ind50 = new javax.swing.JPanel();
        ind47 = new javax.swing.JPanel();
        Basophil = new javax.swing.JTextField();
        ind49 = new javax.swing.JPanel();
        ind28 = new javax.swing.JPanel();
        ind48 = new javax.swing.JPanel();
        mchc = new javax.swing.JTextField();
        mch = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        rdw = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        ind42 = new javax.swing.JPanel();
        hemo = new javax.swing.JTextField();
        INR = new javax.swing.JTextField();
        rbc = new javax.swing.JTextField();
        ind41 = new javax.swing.JPanel();
        PT = new javax.swing.JTextField();
        ind44 = new javax.swing.JPanel();
        ind43 = new javax.swing.JPanel();
        ind39 = new javax.swing.JPanel();
        RBCmorphology = new javax.swing.JTextField();
        Immature = new javax.swing.JTextField();
        aPTT = new javax.swing.JTextField();
        jLabel69 = new javax.swing.JLabel();
        jLabel70 = new javax.swing.JLabel();
        jLabel71 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        jtxtlabcard = new javax.swing.JTextField();
        jLabel67 = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        mcv = new javax.swing.JTextField();
        Differntial = new javax.swing.JTextField();
        hema = new javax.swing.JTextField();
        Neutrophil = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        reticulocyte = new javax.swing.JTextField();
        ESR = new javax.swing.JTextField();
        ind37 = new javax.swing.JPanel();
        platelets = new javax.swing.JTextField();
        MPV = new javax.swing.JTextField();
        jLabel65 = new javax.swing.JLabel();
        ind38 = new javax.swing.JPanel();
        jtxtlabage = new javax.swing.JTextField();
        ind40 = new javax.swing.JPanel();
        jtxtlabName = new javax.swing.JTextField();
        PDW = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jBtnxr = new javax.swing.JButton();
        jLabelxray = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ind26.setBackground(new java.awt.Color(0, 153, 153));
        ind26.setPreferredSize(new java.awt.Dimension(188, 2));

        javax.swing.GroupLayout ind26Layout = new javax.swing.GroupLayout(ind26);
        ind26.setLayout(ind26Layout);
        ind26Layout.setHorizontalGroup(
            ind26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 114, Short.MAX_VALUE)
        );
        ind26Layout.setVerticalGroup(
            ind26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        ind27.setBackground(new java.awt.Color(0, 153, 153));
        ind27.setPreferredSize(new java.awt.Dimension(188, 2));

        javax.swing.GroupLayout ind27Layout = new javax.swing.GroupLayout(ind27);
        ind27.setLayout(ind27Layout);
        ind27Layout.setHorizontalGroup(
            ind27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 114, Short.MAX_VALUE)
        );
        ind27Layout.setVerticalGroup(
            ind27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        btnlabsave.setBackground(new java.awt.Color(0, 153, 153));
        btnlabsave.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btnlabsave.setForeground(new java.awt.Color(255, 255, 255));
        btnlabsave.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnlabsave.setText("Save");
        btnlabsave.setOpaque(true);
        btnlabsave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnlabsaveMouseClicked(evt);
            }
        });

        jLabel74.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jLabel74.setText("Immature cell");

        notes.setColumns(20);
        notes.setRows(5);
        notes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153)));
        jScrollPane4.setViewportView(notes);

        jLabel75.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jLabel75.setText("RBC morphology");

        ind54.setBackground(new java.awt.Color(0, 153, 153));
        ind54.setPreferredSize(new java.awt.Dimension(188, 2));

        javax.swing.GroupLayout ind54Layout = new javax.swing.GroupLayout(ind54);
        ind54.setLayout(ind54Layout);
        ind54Layout.setHorizontalGroup(
            ind54Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 267, Short.MAX_VALUE)
        );
        ind54Layout.setVerticalGroup(
            ind54Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        jLabel72.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jLabel72.setText("Basophil");

        btnlabsearch.setBackground(new java.awt.Color(0, 153, 153));
        btnlabsearch.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btnlabsearch.setForeground(new java.awt.Color(255, 255, 255));
        btnlabsearch.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnlabsearch.setText("Search");
        btnlabsearch.setOpaque(true);
        btnlabsearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnlabsearchMouseClicked(evt);
            }
        });

        jLabel73.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jLabel73.setText("Monocyte");

        jLabel78.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jLabel78.setText("INR");

        ind53.setBackground(new java.awt.Color(0, 153, 153));
        ind53.setPreferredSize(new java.awt.Dimension(188, 2));

        javax.swing.GroupLayout ind53Layout = new javax.swing.GroupLayout(ind53);
        ind53.setLayout(ind53Layout);
        ind53Layout.setHorizontalGroup(
            ind53Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 148, Short.MAX_VALUE)
        );
        ind53Layout.setVerticalGroup(
            ind53Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        ind25.setBackground(new java.awt.Color(0, 153, 153));
        ind25.setPreferredSize(new java.awt.Dimension(188, 2));

        javax.swing.GroupLayout ind25Layout = new javax.swing.GroupLayout(ind25);
        ind25.setLayout(ind25Layout);
        ind25Layout.setHorizontalGroup(
            ind25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        ind25Layout.setVerticalGroup(
            ind25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        jLabel76.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jLabel76.setText("aPTT");

        jLabel77.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jLabel77.setText("PT");

        ind51.setBackground(new java.awt.Color(0, 153, 153));
        ind51.setPreferredSize(new java.awt.Dimension(188, 2));

        javax.swing.GroupLayout ind51Layout = new javax.swing.GroupLayout(ind51);
        ind51.setLayout(ind51Layout);
        ind51Layout.setHorizontalGroup(
            ind51Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 220, Short.MAX_VALUE)
        );
        ind51Layout.setVerticalGroup(
            ind51Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        jtxtlabgender.setEditable(false);
        jtxtlabgender.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jtxtlabgender.setBorder(null);
        jtxtlabgender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtlabgenderActionPerformed(evt);
            }
        });

        jLabel86.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jLabel86.setText("Notes");

        ind36.setBackground(new java.awt.Color(0, 153, 153));
        ind36.setPreferredSize(new java.awt.Dimension(188, 2));

        javax.swing.GroupLayout ind36Layout = new javax.swing.GroupLayout(ind36);
        ind36.setLayout(ind36Layout);
        ind36Layout.setHorizontalGroup(
            ind36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 114, Short.MAX_VALUE)
        );
        ind36Layout.setVerticalGroup(
            ind36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        jLabel20.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jLabel20.setText("Gender:");

        jLabel21.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jLabel21.setText("Age:");

        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jLabel7.setText("Fullname:");

        jLabel22.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jLabel22.setText("Doctor Name:");

        jtxtlabdoctor.setEditable(false);
        jtxtlabdoctor.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jtxtlabdoctor.setBorder(null);
        jtxtlabdoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtlabdoctorActionPerformed(evt);
            }
        });

        Eosinophil.setEditable(false);
        Eosinophil.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        Eosinophil.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Eosinophil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EosinophilActionPerformed(evt);
            }
        });

        wbc.setEditable(false);
        wbc.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        wbc.setText("                     k cells ul");
        wbc.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        wbc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wbcActionPerformed(evt);
            }
        });

        ind29.setBackground(new java.awt.Color(0, 153, 153));
        ind29.setPreferredSize(new java.awt.Dimension(188, 2));

        javax.swing.GroupLayout ind29Layout = new javax.swing.GroupLayout(ind29);
        ind29.setLayout(ind29Layout);
        ind29Layout.setHorizontalGroup(
            ind29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 114, Short.MAX_VALUE)
        );
        ind29Layout.setVerticalGroup(
            ind29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        ind45.setBackground(new java.awt.Color(0, 153, 153));
        ind45.setPreferredSize(new java.awt.Dimension(188, 2));

        javax.swing.GroupLayout ind45Layout = new javax.swing.GroupLayout(ind45);
        ind45.setLayout(ind45Layout);
        ind45Layout.setHorizontalGroup(
            ind45Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 114, Short.MAX_VALUE)
        );
        ind45Layout.setVerticalGroup(
            ind45Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        jLabel16.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jLabel16.setText("platelets count");

        ind30.setBackground(new java.awt.Color(0, 153, 153));
        ind30.setPreferredSize(new java.awt.Dimension(188, 2));

        javax.swing.GroupLayout ind30Layout = new javax.swing.GroupLayout(ind30);
        ind30.setLayout(ind30Layout);
        ind30Layout.setHorizontalGroup(
            ind30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 114, Short.MAX_VALUE)
        );
        ind30Layout.setVerticalGroup(
            ind30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        ind46.setBackground(new java.awt.Color(0, 153, 153));
        ind46.setPreferredSize(new java.awt.Dimension(188, 2));

        javax.swing.GroupLayout ind46Layout = new javax.swing.GroupLayout(ind46);
        ind46.setLayout(ind46Layout);
        ind46Layout.setHorizontalGroup(
            ind46Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 114, Short.MAX_VALUE)
        );
        ind46Layout.setVerticalGroup(
            ind46Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        jLabel8.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jLabel8.setText("RBC count");

        ind31.setBackground(new java.awt.Color(0, 153, 153));
        ind31.setPreferredSize(new java.awt.Dimension(188, 2));

        javax.swing.GroupLayout ind31Layout = new javax.swing.GroupLayout(ind31);
        ind31.setLayout(ind31Layout);
        ind31Layout.setHorizontalGroup(
            ind31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 114, Short.MAX_VALUE)
        );
        ind31Layout.setVerticalGroup(
            ind31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        Monocyte.setEditable(false);
        Monocyte.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        Monocyte.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Monocyte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MonocyteActionPerformed(evt);
            }
        });

        ind33.setBackground(new java.awt.Color(0, 153, 153));
        ind33.setPreferredSize(new java.awt.Dimension(188, 2));

        javax.swing.GroupLayout ind33Layout = new javax.swing.GroupLayout(ind33);
        ind33.setLayout(ind33Layout);
        ind33Layout.setHorizontalGroup(
            ind33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 114, Short.MAX_VALUE)
        );
        ind33Layout.setVerticalGroup(
            ind33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        jLabel15.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jLabel15.setText("Total WBC");

        ind34.setBackground(new java.awt.Color(0, 153, 153));
        ind34.setPreferredSize(new java.awt.Dimension(188, 2));

        javax.swing.GroupLayout ind34Layout = new javax.swing.GroupLayout(ind34);
        ind34.setLayout(ind34Layout);
        ind34Layout.setHorizontalGroup(
            ind34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 114, Short.MAX_VALUE)
        );
        ind34Layout.setVerticalGroup(
            ind34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        Lymphocyte.setEditable(false);
        Lymphocyte.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        Lymphocyte.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Lymphocyte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LymphocyteActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jLabel9.setText("Hemoglobin");

        ind32.setBackground(new java.awt.Color(0, 153, 153));
        ind32.setPreferredSize(new java.awt.Dimension(188, 2));

        javax.swing.GroupLayout ind32Layout = new javax.swing.GroupLayout(ind32);
        ind32.setLayout(ind32Layout);
        ind32Layout.setHorizontalGroup(
            ind32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 114, Short.MAX_VALUE)
        );
        ind32Layout.setVerticalGroup(
            ind32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        ind35.setBackground(new java.awt.Color(0, 153, 153));
        ind35.setPreferredSize(new java.awt.Dimension(188, 2));

        javax.swing.GroupLayout ind35Layout = new javax.swing.GroupLayout(ind35);
        ind35.setLayout(ind35Layout);
        ind35Layout.setHorizontalGroup(
            ind35Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 114, Short.MAX_VALUE)
        );
        ind35Layout.setVerticalGroup(
            ind35Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        ind52.setBackground(new java.awt.Color(0, 153, 153));
        ind52.setPreferredSize(new java.awt.Dimension(188, 2));

        javax.swing.GroupLayout ind52Layout = new javax.swing.GroupLayout(ind52);
        ind52.setLayout(ind52Layout);
        ind52Layout.setHorizontalGroup(
            ind52Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 148, Short.MAX_VALUE)
        );
        ind52Layout.setVerticalGroup(
            ind52Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        ind50.setBackground(new java.awt.Color(0, 153, 153));
        ind50.setPreferredSize(new java.awt.Dimension(188, 2));

        javax.swing.GroupLayout ind50Layout = new javax.swing.GroupLayout(ind50);
        ind50.setLayout(ind50Layout);
        ind50Layout.setHorizontalGroup(
            ind50Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 220, Short.MAX_VALUE)
        );
        ind50Layout.setVerticalGroup(
            ind50Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        ind47.setBackground(new java.awt.Color(0, 153, 153));
        ind47.setPreferredSize(new java.awt.Dimension(188, 2));

        javax.swing.GroupLayout ind47Layout = new javax.swing.GroupLayout(ind47);
        ind47.setLayout(ind47Layout);
        ind47Layout.setHorizontalGroup(
            ind47Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 114, Short.MAX_VALUE)
        );
        ind47Layout.setVerticalGroup(
            ind47Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        Basophil.setEditable(false);
        Basophil.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        Basophil.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Basophil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BasophilActionPerformed(evt);
            }
        });

        ind49.setBackground(new java.awt.Color(0, 153, 153));
        ind49.setPreferredSize(new java.awt.Dimension(188, 2));

        javax.swing.GroupLayout ind49Layout = new javax.swing.GroupLayout(ind49);
        ind49.setLayout(ind49Layout);
        ind49Layout.setHorizontalGroup(
            ind49Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 114, Short.MAX_VALUE)
        );
        ind49Layout.setVerticalGroup(
            ind49Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        ind28.setBackground(new java.awt.Color(0, 153, 153));
        ind28.setPreferredSize(new java.awt.Dimension(188, 2));

        javax.swing.GroupLayout ind28Layout = new javax.swing.GroupLayout(ind28);
        ind28.setLayout(ind28Layout);
        ind28Layout.setHorizontalGroup(
            ind28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 114, Short.MAX_VALUE)
        );
        ind28Layout.setVerticalGroup(
            ind28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        ind48.setBackground(new java.awt.Color(0, 153, 153));
        ind48.setPreferredSize(new java.awt.Dimension(188, 2));

        javax.swing.GroupLayout ind48Layout = new javax.swing.GroupLayout(ind48);
        ind48.setLayout(ind48Layout);
        ind48Layout.setHorizontalGroup(
            ind48Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 114, Short.MAX_VALUE)
        );
        ind48Layout.setVerticalGroup(
            ind48Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        mchc.setEditable(false);
        mchc.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        mchc.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        mchc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mchcActionPerformed(evt);
            }
        });

        mch.setEditable(false);
        mch.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        mch.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        mch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mchActionPerformed(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jLabel24.setText("RDW");

        rdw.setEditable(false);
        rdw.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        rdw.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        rdw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdwActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jLabel14.setText("MCH");

        jLabel23.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jLabel23.setText("MCHC");

        jLabel11.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jLabel11.setText("Hemaocrit");

        jLabel13.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jLabel13.setText("MCV");

        ind42.setBackground(new java.awt.Color(0, 153, 153));
        ind42.setPreferredSize(new java.awt.Dimension(188, 2));

        javax.swing.GroupLayout ind42Layout = new javax.swing.GroupLayout(ind42);
        ind42.setLayout(ind42Layout);
        ind42Layout.setHorizontalGroup(
            ind42Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 114, Short.MAX_VALUE)
        );
        ind42Layout.setVerticalGroup(
            ind42Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        hemo.setEditable(false);
        hemo.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        hemo.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        hemo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hemoActionPerformed(evt);
            }
        });

        INR.setEditable(false);
        INR.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        INR.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        INR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                INRActionPerformed(evt);
            }
        });

        rbc.setEditable(false);
        rbc.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        rbc.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        rbc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbcActionPerformed(evt);
            }
        });

        ind41.setBackground(new java.awt.Color(0, 153, 153));
        ind41.setPreferredSize(new java.awt.Dimension(188, 2));

        javax.swing.GroupLayout ind41Layout = new javax.swing.GroupLayout(ind41);
        ind41.setLayout(ind41Layout);
        ind41Layout.setHorizontalGroup(
            ind41Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 114, Short.MAX_VALUE)
        );
        ind41Layout.setVerticalGroup(
            ind41Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        PT.setEditable(false);
        PT.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        PT.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        PT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PTActionPerformed(evt);
            }
        });

        ind44.setBackground(new java.awt.Color(0, 153, 153));
        ind44.setPreferredSize(new java.awt.Dimension(188, 2));

        javax.swing.GroupLayout ind44Layout = new javax.swing.GroupLayout(ind44);
        ind44.setLayout(ind44Layout);
        ind44Layout.setHorizontalGroup(
            ind44Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 114, Short.MAX_VALUE)
        );
        ind44Layout.setVerticalGroup(
            ind44Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        ind43.setBackground(new java.awt.Color(0, 153, 153));
        ind43.setPreferredSize(new java.awt.Dimension(188, 2));

        javax.swing.GroupLayout ind43Layout = new javax.swing.GroupLayout(ind43);
        ind43.setLayout(ind43Layout);
        ind43Layout.setHorizontalGroup(
            ind43Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 114, Short.MAX_VALUE)
        );
        ind43Layout.setVerticalGroup(
            ind43Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        ind39.setBackground(new java.awt.Color(0, 153, 153));
        ind39.setPreferredSize(new java.awt.Dimension(188, 2));

        javax.swing.GroupLayout ind39Layout = new javax.swing.GroupLayout(ind39);
        ind39.setLayout(ind39Layout);
        ind39Layout.setHorizontalGroup(
            ind39Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 114, Short.MAX_VALUE)
        );
        ind39Layout.setVerticalGroup(
            ind39Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        RBCmorphology.setEditable(false);
        RBCmorphology.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        RBCmorphology.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        RBCmorphology.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBCmorphologyActionPerformed(evt);
            }
        });

        Immature.setEditable(false);
        Immature.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        Immature.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Immature.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ImmatureActionPerformed(evt);
            }
        });

        aPTT.setEditable(false);
        aPTT.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        aPTT.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        aPTT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aPTTActionPerformed(evt);
            }
        });

        jLabel69.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jLabel69.setText("Neutrophil");

        jLabel70.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jLabel70.setText("Lymphocyte");

        jLabel71.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jLabel71.setText("Eosinophil");

        jLabel33.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jLabel33.setText("MPV");

        jLabel66.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jLabel66.setText("ESR");

        jtxtlabcard.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jtxtlabcard.setBorder(null);
        jtxtlabcard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtlabcardActionPerformed(evt);
            }
        });

        jLabel67.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jLabel67.setText("Reticulocyte count");

        jLabel68.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jLabel68.setText("Differntial");

        mcv.setEditable(false);
        mcv.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        mcv.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        mcv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mcvActionPerformed(evt);
            }
        });

        Differntial.setEditable(false);
        Differntial.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        Differntial.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Differntial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DifferntialActionPerformed(evt);
            }
        });

        hema.setEditable(false);
        hema.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        hema.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        hema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hemaActionPerformed(evt);
            }
        });

        Neutrophil.setEditable(false);
        Neutrophil.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        Neutrophil.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Neutrophil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NeutrophilActionPerformed(evt);
            }
        });

        jLabel26.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jLabel26.setText("PDW");

        reticulocyte.setEditable(false);
        reticulocyte.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        reticulocyte.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        reticulocyte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reticulocyteActionPerformed(evt);
            }
        });

        ESR.setEditable(false);
        ESR.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        ESR.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        ESR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ESRActionPerformed(evt);
            }
        });

        ind37.setBackground(new java.awt.Color(0, 153, 153));
        ind37.setPreferredSize(new java.awt.Dimension(188, 2));

        javax.swing.GroupLayout ind37Layout = new javax.swing.GroupLayout(ind37);
        ind37.setLayout(ind37Layout);
        ind37Layout.setHorizontalGroup(
            ind37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 114, Short.MAX_VALUE)
        );
        ind37Layout.setVerticalGroup(
            ind37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        platelets.setEditable(false);
        platelets.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        platelets.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        platelets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plateletsActionPerformed(evt);
            }
        });

        MPV.setEditable(false);
        MPV.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        MPV.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        MPV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MPVActionPerformed(evt);
            }
        });

        jLabel65.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jLabel65.setText("Card Number");

        ind38.setBackground(new java.awt.Color(0, 153, 153));
        ind38.setPreferredSize(new java.awt.Dimension(188, 2));

        javax.swing.GroupLayout ind38Layout = new javax.swing.GroupLayout(ind38);
        ind38.setLayout(ind38Layout);
        ind38Layout.setHorizontalGroup(
            ind38Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 114, Short.MAX_VALUE)
        );
        ind38Layout.setVerticalGroup(
            ind38Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        jtxtlabage.setEditable(false);
        jtxtlabage.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jtxtlabage.setBorder(null);
        jtxtlabage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtlabageActionPerformed(evt);
            }
        });

        ind40.setBackground(new java.awt.Color(0, 153, 153));
        ind40.setPreferredSize(new java.awt.Dimension(188, 2));

        javax.swing.GroupLayout ind40Layout = new javax.swing.GroupLayout(ind40);
        ind40.setLayout(ind40Layout);
        ind40Layout.setHorizontalGroup(
            ind40Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 114, Short.MAX_VALUE)
        );
        ind40Layout.setVerticalGroup(
            ind40Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        jtxtlabName.setEditable(false);
        jtxtlabName.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jtxtlabName.setBorder(null);
        jtxtlabName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtlabNameActionPerformed(evt);
            }
        });

        PDW.setEditable(false);
        PDW.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        PDW.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        PDW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PDWActionPerformed(evt);
            }
        });

        jLabel1.setText("X-Ray and Others");

        jBtnxr.setText("Upload");
        jBtnxr.setEnabled(false);
        jBtnxr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnxrActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ind25, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 946, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addComponent(jLabel65)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ind54, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtlabcard, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel20)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jtxtlabName, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ind50, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jtxtlabgender, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ind51, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22)
                            .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ind52, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                            .addComponent(ind53, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                            .addComponent(jtxtlabage)
                            .addComponent(jtxtlabdoctor)))
                    .addComponent(btnlabsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(jLabel8)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addComponent(jLabel23)
                            .addComponent(jLabel24)
                            .addComponent(jLabel86))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(mcv, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ind29, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ind34, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(wbc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(rbc, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ind26, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(hemo, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ind27, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(hema, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ind28, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(mch, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ind30, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(mchc, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ind31, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(rdw, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ind33, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel66)
                            .addComponent(jLabel33)
                            .addComponent(jLabel26)
                            .addComponent(jLabel16)
                            .addComponent(jLabel67)
                            .addComponent(jLabel68)
                            .addComponent(jLabel69)
                            .addComponent(jLabel70))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(reticulocyte, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                            .addComponent(ind36, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                            .addComponent(ind41, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                            .addComponent(PDW)
                            .addComponent(ind38, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                            .addComponent(MPV)
                            .addComponent(ind37, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                            .addComponent(ESR)
                            .addComponent(ind32, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                            .addComponent(Differntial)
                            .addComponent(ind35, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                            .addComponent(Neutrophil)
                            .addComponent(ind40, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                            .addComponent(Lymphocyte)
                            .addComponent(ind42, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                            .addComponent(platelets))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel73)
                                    .addComponent(jLabel71)
                                    .addComponent(jLabel72)
                                    .addComponent(jLabel74)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel75)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(26, 26, 26)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel76)
                                            .addComponent(jLabel77)
                                            .addComponent(jLabel78))))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(RBCmorphology, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                            .addComponent(ind44, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                            .addComponent(ind48, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                            .addComponent(Basophil)
                            .addComponent(ind46, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                            .addComponent(Monocyte)
                            .addComponent(ind45, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                            .addComponent(Immature)
                            .addComponent(ind39, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                            .addComponent(PT)
                            .addComponent(ind43, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                            .addComponent(aPTT)
                            .addComponent(ind47, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                            .addComponent(INR)
                            .addComponent(ind49, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                            .addComponent(Eosinophil))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnlabsave, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBtnxr)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelxray, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(23, 23, 23))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel65, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtlabcard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, 0)
                        .addComponent(ind54, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnlabsearch, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(1, 1, 1))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jtxtlabage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(ind52, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jtxtlabdoctor, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(ind53, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jtxtlabName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(ind50, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtxtlabgender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20))
                        .addGap(0, 0, 0)
                        .addComponent(ind51, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addComponent(ind25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Eosinophil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(ind46, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Basophil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(ind45, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Monocyte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(ind39, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Immature, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(ind44, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(RBCmorphology, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(ind43, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(PT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(ind47, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(aPTT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(1, 1, 1)
                                .addComponent(ind49, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(INR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(ind48, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(platelets, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(ind38, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(PDW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(ind37, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(MPV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(ind32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ESR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(ind36, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(reticulocyte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(ind35, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Differntial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(ind40, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Neutrophil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel76))
                                .addGap(1, 1, 1)
                                .addComponent(ind42, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Lymphocyte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(ind41, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnlabsave, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(jLabel86)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(wbc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16)
                            .addComponent(jLabel71))
                        .addComponent(ind26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel26)
                            .addComponent(jLabel72))
                        .addComponent(ind27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(hemo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel33)
                            .addComponent(jLabel73))
                        .addComponent(ind28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel11)
                                .addComponent(hema, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel66))
                            .addComponent(jLabel74))
                        .addGap(0, 0, 0)
                        .addComponent(ind29, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mcv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel67)
                            .addComponent(jLabel75))
                        .addGap(0, 0, 0)
                        .addComponent(ind30, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel14)
                                .addComponent(mch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel68))
                            .addComponent(jLabel77))
                        .addGap(0, 0, 0)
                        .addComponent(ind31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(mchc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23)
                            .addComponent(jLabel69))
                        .addGap(1, 1, 1)
                        .addComponent(ind33, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jLabel78))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(rdw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel24))
                                .addGap(0, 0, 0)
                                .addComponent(ind34, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel70)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jBtnxr)
                            .addComponent(jLabelxray, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 
 
  
    private void DBConnect() {
        try {
            con = DriverManager.getConnection(
                    server, "root", "John-1995"
            );

        } catch (SQLException sqlException) {
            sqlException.printStackTrace();
        }

    }
    public String getRequested(int reqID) {
        String requests = null;
        try {
            sql = con.createStatement();
            rs = sql.executeQuery(
                    "Select requestd From labrequests where requestnumber=" + this.reqID);
            while (rs.next()) {

                requests = rs.getString("requestd");

            }
            rs.close();
            sql.close();
        } catch (SQLException sqlException) {
            sqlException.printStackTrace();
        }
        return requests;
    }
      public void labse() {
        try {
            sql = con.createStatement();
            rs = sql.executeQuery(
                    "select CardNumber,Name from patient "
                    + "where Name= " + "'" + jtxtlabName.getText() + "'");
            while (rs.next()) {
                String ID = rs.getString("CardNumber");
                JOptionPane.showMessageDialog(null, "patinet result  Successfully Added! With card number " + ID);
            }
            sql.close();
        } catch (SQLException e) {
            e.printStackTrace();
        }

    }  
    private void btnlabsaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnlabsaveMouseClicked
try {
            int result = 0;
            String cn = this.jtxtlabcard.getText();
            String name = this.jtxtlabName.getText();
            String gend = this.jtxtlabgender.getText();
            String Age = this.jtxtlabage.getText();
            String doct = this.jtxtlabdoctor.getText();
            String wb = this.wbc.getText();
            String rb = this.rbc.getText();
            String hem = this.hemo.getText();
            String hemaa = this.hema.getText();
            String mc = this.mcv.getText();
            String mcha = this.mch.getText();
            String mchhc = this.mchc.getText();
            String rd = this.rdw.getText();
            String pla = this.platelets.getText();
            String pd = this.PDW.getText();
            String mp = this.MPV.getText();
            String es = this.ESR.getText();
            String rec = this.reticulocyte.getText();
            String dif = this.Differntial.getText();
            String neu = this.Neutrophil.getText();
            String ly = this.Lymphocyte.getText();
            String eos = this.Eosinophil.getText();
            String bas = this.Basophil.getText();
            String mon = this.Monocyte.getText();
            String imat = this.Immature.getText();
            String rbcc = this.RBCmorphology.getText();
            String ptt = this.PT.getText();
            String apt = this.aPTT.getText();
            String in = this.INR.getText();
            String note = this.notes.getText();

            labres = con.prepareStatement(
                    " insert into labresult (cardnumber,name,age,gender,doctorname,"
                    + "wbc,rbc,hemoglobin,Hemaocrit,MCV,MCH,MCHC,RDW,plateletscount,PDW,MPV,ESR"
                    + ",Reticulocytecount,Differntial,Neutrophil,Lymphocyte,Eosinophil,Basophil,"
                    + "Monocyte,Immaturecell,RBCmorphology,PT,aPTT,INR,notes,checkedby,xray)"
                    + " values (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)"
            );
            labres.setString(1, cn);
            labres.setString(2, name);
            labres.setString(3, Age);
            labres.setString(4, gend);
            labres.setString(5, doct);
            labres.setString(6, wb);
            labres.setString(7, rb);
            labres.setString(8, hem);
            labres.setString(9, hemaa);
            labres.setString(10, mc);
            labres.setString(11, mcha);
            labres.setString(12, mchhc);
            labres.setString(13, rd);
            labres.setString(14, pla);
            labres.setString(15, pd);
            labres.setString(16, mp);
            labres.setString(17, es);
            labres.setString(18, rec);
            labres.setString(19, dif);
            labres.setString(20, neu);
            labres.setString(21, ly);
            labres.setString(22, eos);
            labres.setString(23, bas);
            labres.setString(24, mon);
            labres.setString(25, imat);
            labres.setString(26, rbcc);
            labres.setString(27, ptt);
            labres.setString(28, apt);
            labres.setString(29, in);
            labres.setString(30, note);
            Cpm uname=new Cpm ();
            String x=uname.txtUserId.getText();
            labres.setString(31,x);
            labres.setBytes(32, rimage);

            result = labres.executeUpdate();
            labse();
            labres.close();

        } catch (SQLException s) {
            JOptionPane.showMessageDialog(null, "Make sure that you entered all the fields");
            s.printStackTrace();
        }
   
    }//GEN-LAST:event_btnlabsaveMouseClicked

    private void btnlabsearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnlabsearchMouseClicked
        // TODO add your handling code here:
        try {
            String cnumber = jtxtlabcard.getText();
            sql = con.createStatement();
            labrs = sql.executeQuery(
                "select * from patient where CardNumber=" + cnumber);

            while (labrs.next()) {
                jtxtlabcard.setText(labrs.getString("CardNumber"));
                jtxtlabName.setText(labrs.getString("Name"));
                jtxtlabage.setText(labrs.getString("Age"));
                jtxtlabdoctor.setText(labrs.getString("Doctor"));
                jtxtlabgender.setText(labrs.getString("Gender"));
            }
            labrs.close();
            sql.close();

        } catch (SQLException sqlException) {
            sqlException.printStackTrace();
        }
    }//GEN-LAST:event_btnlabsearchMouseClicked

    private void jtxtlabgenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtlabgenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtlabgenderActionPerformed

    private void jtxtlabdoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtlabdoctorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtlabdoctorActionPerformed

    private void EosinophilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EosinophilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EosinophilActionPerformed

    private void wbcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wbcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_wbcActionPerformed

    private void MonocyteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MonocyteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MonocyteActionPerformed

    private void LymphocyteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LymphocyteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LymphocyteActionPerformed

    private void BasophilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BasophilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BasophilActionPerformed

    private void mchcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mchcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mchcActionPerformed

    private void mchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mchActionPerformed

    private void rdwActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdwActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdwActionPerformed

    private void hemoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hemoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hemoActionPerformed

    private void INRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_INRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_INRActionPerformed

    private void rbcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbcActionPerformed

    private void PTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PTActionPerformed

    private void RBCmorphologyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBCmorphologyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RBCmorphologyActionPerformed

    private void ImmatureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ImmatureActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ImmatureActionPerformed

    private void aPTTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aPTTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aPTTActionPerformed

    private void jtxtlabcardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtlabcardActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtlabcardActionPerformed

    private void mcvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mcvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mcvActionPerformed

    private void DifferntialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DifferntialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DifferntialActionPerformed

    private void hemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hemaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hemaActionPerformed

    private void NeutrophilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NeutrophilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NeutrophilActionPerformed

    private void reticulocyteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reticulocyteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_reticulocyteActionPerformed

    private void ESRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ESRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ESRActionPerformed

    private void plateletsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plateletsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_plateletsActionPerformed

    private void MPVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MPVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MPVActionPerformed

    private void jtxtlabageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtlabageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtlabageActionPerformed

    private void jtxtlabNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtlabNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtlabNameActionPerformed

    private void PDWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PDWActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PDWActionPerformed
 String aname ; 
    private void jBtnxrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnxrActionPerformed
        // TODO add your handling code here:
         FileFilter filter = new FileNameExtensionFilter("PNG", "JPEG", "BMP");
        JFileChooser chooser = new JFileChooser("");
        chooser.addChoosableFileFilter(filter);
        int returnVal = chooser.showOpenDialog(null);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            aname = chooser.getSelectedFile().getAbsolutePath();
            jLabelxray.setText(aname);
        }
        try {
            File image = new File(aname);
            FileInputStream fis = new FileInputStream(image);
            ByteArrayOutputStream bos = new ByteArrayOutputStream();
            byte[] buf = new byte[1024];
            for (int readNum; (readNum = fis.read(buf)) != -1;) {
                bos.write(buf, 0, readNum);
            }
            rimage = bos.toByteArray();
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "File is not selected");
        }
    }//GEN-LAST:event_jBtnxrActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cpmresult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cpmresult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cpmresult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cpmresult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cpmresult().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField Basophil;
    public javax.swing.JTextField Differntial;
    public javax.swing.JTextField ESR;
    public javax.swing.JTextField Eosinophil;
    public javax.swing.JTextField INR;
    public javax.swing.JTextField Immature;
    public javax.swing.JTextField Lymphocyte;
    public javax.swing.JTextField MPV;
    public javax.swing.JTextField Monocyte;
    public javax.swing.JTextField Neutrophil;
    public javax.swing.JTextField PDW;
    public javax.swing.JTextField PT;
    public javax.swing.JTextField RBCmorphology;
    public javax.swing.JTextField aPTT;
    private javax.swing.JLabel btnlabsave;
    private javax.swing.JLabel btnlabsearch;
    public javax.swing.JTextField hema;
    public javax.swing.JTextField hemo;
    private javax.swing.JPanel ind25;
    private javax.swing.JPanel ind26;
    private javax.swing.JPanel ind27;
    private javax.swing.JPanel ind28;
    private javax.swing.JPanel ind29;
    private javax.swing.JPanel ind30;
    private javax.swing.JPanel ind31;
    private javax.swing.JPanel ind32;
    public javax.swing.JPanel ind33;
    private javax.swing.JPanel ind34;
    private javax.swing.JPanel ind35;
    private javax.swing.JPanel ind36;
    private javax.swing.JPanel ind37;
    private javax.swing.JPanel ind38;
    private javax.swing.JPanel ind39;
    private javax.swing.JPanel ind40;
    private javax.swing.JPanel ind41;
    private javax.swing.JPanel ind42;
    private javax.swing.JPanel ind43;
    private javax.swing.JPanel ind44;
    private javax.swing.JPanel ind45;
    private javax.swing.JPanel ind46;
    private javax.swing.JPanel ind47;
    private javax.swing.JPanel ind48;
    private javax.swing.JPanel ind49;
    private javax.swing.JPanel ind50;
    private javax.swing.JPanel ind51;
    private javax.swing.JPanel ind52;
    private javax.swing.JPanel ind53;
    private javax.swing.JPanel ind54;
    public javax.swing.JButton jBtnxr;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel86;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelxray;
    private javax.swing.JScrollPane jScrollPane4;
    public javax.swing.JTextField jtxtlabName;
    public javax.swing.JTextField jtxtlabage;
    public javax.swing.JTextField jtxtlabcard;
    public javax.swing.JTextField jtxtlabdoctor;
    public javax.swing.JTextField jtxtlabgender;
    public javax.swing.JTextField mch;
    public javax.swing.JTextField mchc;
    public javax.swing.JTextField mcv;
    public javax.swing.JTextArea notes;
    public javax.swing.JTextField platelets;
    public javax.swing.JTextField rbc;
    public javax.swing.JTextField rdw;
    public javax.swing.JTextField reticulocyte;
    public javax.swing.JTextField wbc;
    // End of variables declaration//GEN-END:variables
}
