/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Admin;

import static Admin.cpmresult.server;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author john
 */
public class Refree extends javax.swing.JFrame {
static final String server = "jdbc:mysql://localhost/cpm";
    public String card_number = "";
        byte[] rimage = null;
    private static int reqID = 0;
    private static int cardNo = 0;
    private PreparedStatement addpat, idp, labres = null;
    private PreparedStatement addpay = null;
    
    ResultSet rs = null;
    Connection con = null;
    Statement sql = null;
    ResultSet labrs;
    /**
     * Creates new form Refree
     */
    public Refree() {
        initComponents();
        DBConnect();
    }
 private void DBConnect() {
        try {
            con = DriverManager.getConnection(
                    server, "root", "John-1995"
            );

        } catch (SQLException sqlException) {
            sqlException.printStackTrace();
        }

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpAddPatient = new javax.swing.JPanel();
        ind9 = new javax.swing.JPanel();
        txtPAge = new javax.swing.JTextField();
        ind10 = new javax.swing.JPanel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        btnAddPatient = new javax.swing.JLabel();
        txtPDr = new javax.swing.JTextField();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        txtPDate = new javax.swing.JTextField();
        jLabel57 = new javax.swing.JLabel();
        ind11 = new javax.swing.JPanel();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        txtPname = new javax.swing.JTextField();
        jLabel61 = new javax.swing.JLabel();
        ind12 = new javax.swing.JPanel();
        ind13 = new javax.swing.JPanel();
        txtPWeghit = new javax.swing.JTextField();
        ind14 = new javax.swing.JPanel();
        txtPRoom = new javax.swing.JTextField();
        ind15 = new javax.swing.JPanel();
        txtPBT = new javax.swing.JTextField();
        ind16 = new javax.swing.JPanel();
        txtPulse = new javax.swing.JTextField();
        jLabel62 = new javax.swing.JLabel();
        ind17 = new javax.swing.JPanel();
        txtPRT = new javax.swing.JTextField();
        jLabel63 = new javax.swing.JLabel();
        ind18 = new javax.swing.JPanel();
        txtPBP = new javax.swing.JTextField();
        jLabel64 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtPNote = new javax.swing.JTextArea();
        jLabel79 = new javax.swing.JLabel();
        txtPno = new javax.swing.JTextField();
        ind19 = new javax.swing.JPanel();
        cbPGenderr = new javax.swing.JTextField();
        ind20 = new javax.swing.JPanel();
        cbPBloodr = new javax.swing.JTextField();
        ind21 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jpAddPatient.setBackground(new java.awt.Color(255, 255, 255));
        jpAddPatient.setPreferredSize(new java.awt.Dimension(750, 430));

        ind9.setBackground(new java.awt.Color(0, 153, 153));
        ind9.setPreferredSize(new java.awt.Dimension(188, 2));

        javax.swing.GroupLayout ind9Layout = new javax.swing.GroupLayout(ind9);
        ind9.setLayout(ind9Layout);
        ind9Layout.setHorizontalGroup(
            ind9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 125, Short.MAX_VALUE)
        );
        ind9Layout.setVerticalGroup(
            ind9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        txtPAge.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtPAge.setBorder(null);

        ind10.setBackground(new java.awt.Color(0, 153, 153));
        ind10.setPreferredSize(new java.awt.Dimension(188, 2));

        javax.swing.GroupLayout ind10Layout = new javax.swing.GroupLayout(ind10);
        ind10.setLayout(ind10Layout);
        ind10Layout.setHorizontalGroup(
            ind10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 125, Short.MAX_VALUE)
        );
        ind10Layout.setVerticalGroup(
            ind10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        jLabel52.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel52.setForeground(new java.awt.Color(0, 153, 153));
        jLabel52.setText("Room Number");

        jLabel53.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel53.setForeground(new java.awt.Color(0, 153, 153));
        jLabel53.setText("Weghit(kg)");

        jLabel54.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel54.setForeground(new java.awt.Color(0, 153, 153));
        jLabel54.setText("Full Name");

        jLabel39.setFont(new java.awt.Font("Century Gothic", 0, 36)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(0, 153, 153));
        jLabel39.setText("ADD PATIENT");

        btnAddPatient.setBackground(new java.awt.Color(0, 153, 153));
        btnAddPatient.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        btnAddPatient.setForeground(new java.awt.Color(255, 255, 255));
        btnAddPatient.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnAddPatient.setText("ADD");
        btnAddPatient.setOpaque(true);
        btnAddPatient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddPatientMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAddPatientMouseEntered(evt);
            }
        });

        txtPDr.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtPDr.setBorder(null);

        jLabel55.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel55.setForeground(new java.awt.Color(0, 153, 153));
        jLabel55.setText("Age");

        jLabel56.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel56.setForeground(new java.awt.Color(0, 153, 153));
        jLabel56.setText("Date");

        txtPDate.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtPDate.setBorder(null);

        jLabel57.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel57.setForeground(new java.awt.Color(0, 153, 153));
        jLabel57.setText("Blood Group");

        ind11.setBackground(new java.awt.Color(0, 153, 153));
        ind11.setPreferredSize(new java.awt.Dimension(188, 2));

        javax.swing.GroupLayout ind11Layout = new javax.swing.GroupLayout(ind11);
        ind11.setLayout(ind11Layout);
        ind11Layout.setHorizontalGroup(
            ind11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 125, Short.MAX_VALUE)
        );
        ind11Layout.setVerticalGroup(
            ind11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        jLabel58.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel58.setForeground(new java.awt.Color(0, 153, 153));
        jLabel58.setText("Gender");

        jLabel59.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel59.setForeground(new java.awt.Color(0, 153, 153));
        jLabel59.setText("Temp. (Body)");

        jLabel60.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel60.setForeground(new java.awt.Color(0, 153, 153));
        jLabel60.setText("Pulse rate");

        txtPname.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtPname.setBorder(null);
        txtPname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPnameActionPerformed(evt);
            }
        });

        jLabel61.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel61.setForeground(new java.awt.Color(0, 153, 153));
        jLabel61.setText("Dr. Name");

        ind12.setBackground(new java.awt.Color(0, 153, 153));
        ind12.setPreferredSize(new java.awt.Dimension(188, 2));

        javax.swing.GroupLayout ind12Layout = new javax.swing.GroupLayout(ind12);
        ind12.setLayout(ind12Layout);
        ind12Layout.setHorizontalGroup(
            ind12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 303, Short.MAX_VALUE)
        );
        ind12Layout.setVerticalGroup(
            ind12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        ind13.setBackground(new java.awt.Color(0, 153, 153));
        ind13.setPreferredSize(new java.awt.Dimension(188, 2));

        javax.swing.GroupLayout ind13Layout = new javax.swing.GroupLayout(ind13);
        ind13.setLayout(ind13Layout);
        ind13Layout.setHorizontalGroup(
            ind13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 303, Short.MAX_VALUE)
        );
        ind13Layout.setVerticalGroup(
            ind13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        txtPWeghit.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtPWeghit.setBorder(null);

        ind14.setBackground(new java.awt.Color(0, 153, 153));
        ind14.setPreferredSize(new java.awt.Dimension(188, 2));

        javax.swing.GroupLayout ind14Layout = new javax.swing.GroupLayout(ind14);
        ind14.setLayout(ind14Layout);
        ind14Layout.setHorizontalGroup(
            ind14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 303, Short.MAX_VALUE)
        );
        ind14Layout.setVerticalGroup(
            ind14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        txtPRoom.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtPRoom.setBorder(null);

        ind15.setBackground(new java.awt.Color(0, 153, 153));
        ind15.setPreferredSize(new java.awt.Dimension(188, 2));

        javax.swing.GroupLayout ind15Layout = new javax.swing.GroupLayout(ind15);
        ind15.setLayout(ind15Layout);
        ind15Layout.setHorizontalGroup(
            ind15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 303, Short.MAX_VALUE)
        );
        ind15Layout.setVerticalGroup(
            ind15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        txtPBT.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtPBT.setBorder(null);

        ind16.setBackground(new java.awt.Color(0, 153, 153));
        ind16.setPreferredSize(new java.awt.Dimension(188, 2));

        javax.swing.GroupLayout ind16Layout = new javax.swing.GroupLayout(ind16);
        ind16.setLayout(ind16Layout);
        ind16Layout.setHorizontalGroup(
            ind16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 303, Short.MAX_VALUE)
        );
        ind16Layout.setVerticalGroup(
            ind16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        txtPulse.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtPulse.setBorder(null);

        jLabel62.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel62.setForeground(new java.awt.Color(0, 153, 153));
        jLabel62.setText("Temp. (Res.)");

        ind17.setBackground(new java.awt.Color(0, 153, 153));
        ind17.setPreferredSize(new java.awt.Dimension(188, 2));

        javax.swing.GroupLayout ind17Layout = new javax.swing.GroupLayout(ind17);
        ind17.setLayout(ind17Layout);
        ind17Layout.setHorizontalGroup(
            ind17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 303, Short.MAX_VALUE)
        );
        ind17Layout.setVerticalGroup(
            ind17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        txtPRT.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtPRT.setBorder(null);

        jLabel63.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel63.setForeground(new java.awt.Color(0, 153, 153));
        jLabel63.setText("Blood Pressure");

        ind18.setBackground(new java.awt.Color(0, 153, 153));
        ind18.setPreferredSize(new java.awt.Dimension(188, 2));

        javax.swing.GroupLayout ind18Layout = new javax.swing.GroupLayout(ind18);
        ind18.setLayout(ind18Layout);
        ind18Layout.setHorizontalGroup(
            ind18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 303, Short.MAX_VALUE)
        );
        ind18Layout.setVerticalGroup(
            ind18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        txtPBP.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtPBP.setBorder(null);
        txtPBP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPBPActionPerformed(evt);
            }
        });

        jLabel64.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel64.setForeground(new java.awt.Color(0, 153, 153));
        jLabel64.setText("Notes");

        txtPNote.setColumns(20);
        txtPNote.setRows(5);
        jScrollPane1.setViewportView(txtPNote);

        jLabel79.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel79.setForeground(new java.awt.Color(0, 153, 153));
        jLabel79.setText("Phone number");

        txtPno.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtPno.setBorder(null);
        txtPno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPnoActionPerformed(evt);
            }
        });

        ind19.setBackground(new java.awt.Color(0, 153, 153));
        ind19.setPreferredSize(new java.awt.Dimension(188, 2));

        javax.swing.GroupLayout ind19Layout = new javax.swing.GroupLayout(ind19);
        ind19.setLayout(ind19Layout);
        ind19Layout.setHorizontalGroup(
            ind19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 303, Short.MAX_VALUE)
        );
        ind19Layout.setVerticalGroup(
            ind19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        cbPGenderr.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        cbPGenderr.setBorder(null);

        ind20.setBackground(new java.awt.Color(0, 153, 153));
        ind20.setPreferredSize(new java.awt.Dimension(188, 2));

        javax.swing.GroupLayout ind20Layout = new javax.swing.GroupLayout(ind20);
        ind20.setLayout(ind20Layout);
        ind20Layout.setHorizontalGroup(
            ind20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 125, Short.MAX_VALUE)
        );
        ind20Layout.setVerticalGroup(
            ind20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        cbPBloodr.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        cbPBloodr.setBorder(null);

        ind21.setBackground(new java.awt.Color(0, 153, 153));
        ind21.setPreferredSize(new java.awt.Dimension(188, 2));

        javax.swing.GroupLayout ind21Layout = new javax.swing.GroupLayout(ind21);
        ind21.setLayout(ind21Layout);
        ind21Layout.setHorizontalGroup(
            ind21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 125, Short.MAX_VALUE)
        );
        ind21Layout.setVerticalGroup(
            ind21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jpAddPatientLayout = new javax.swing.GroupLayout(jpAddPatient);
        jpAddPatient.setLayout(jpAddPatientLayout);
        jpAddPatientLayout.setHorizontalGroup(
            jpAddPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpAddPatientLayout.createSequentialGroup()
                .addGap(0, 33, Short.MAX_VALUE)
                .addGroup(jpAddPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpAddPatientLayout.createSequentialGroup()
                        .addGroup(jpAddPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpAddPatientLayout.createSequentialGroup()
                                .addComponent(jLabel54, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addGroup(jpAddPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtPname, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ind13, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(137, 137, 137)
                                .addComponent(jLabel58)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jpAddPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbPGenderr, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ind20, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jpAddPatientLayout.createSequentialGroup()
                                .addGroup(jpAddPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jpAddPatientLayout.createSequentialGroup()
                                        .addComponent(jLabel53, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(10, 10, 10)
                                        .addComponent(txtPWeghit, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(103, 103, 103)
                                        .addComponent(jLabel57)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jpAddPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cbPBloodr, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(ind21, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jpAddPatientLayout.createSequentialGroup()
                                        .addComponent(jLabel62, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(10, 10, 10)
                                        .addGroup(jpAddPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtPRT, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(ind17, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jpAddPatientLayout.createSequentialGroup()
                                        .addComponent(jLabel63, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(10, 10, 10)
                                        .addGroup(jpAddPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtPBP, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(ind18, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jpAddPatientLayout.createSequentialGroup()
                                        .addGap(127, 127, 127)
                                        .addComponent(ind12, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jpAddPatientLayout.createSequentialGroup()
                                        .addComponent(jLabel52)
                                        .addGap(28, 28, 28)
                                        .addGroup(jpAddPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtPRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(ind14, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(160, 160, 160)
                                        .addComponent(jLabel55)
                                        .addGap(3, 3, 3)
                                        .addComponent(txtPAge, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jpAddPatientLayout.createSequentialGroup()
                                        .addGap(620, 620, 620)
                                        .addComponent(ind10, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jpAddPatientLayout.createSequentialGroup()
                                        .addGap(624, 624, 624)
                                        .addComponent(ind11, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jpAddPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jpAddPatientLayout.createSequentialGroup()
                                            .addComponent(jLabel59, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(28, 28, 28)
                                            .addGroup(jpAddPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(txtPBT, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(ind15, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(146, 146, 146)
                                            .addComponent(jLabel56)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(txtPDate, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(ind9, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jpAddPatientLayout.createSequentialGroup()
                                        .addGroup(jpAddPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpAddPatientLayout.createSequentialGroup()
                                                .addComponent(jLabel64)
                                                .addGap(18, 18, 18))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpAddPatientLayout.createSequentialGroup()
                                                .addComponent(btnAddPatient, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(127, 127, 127))
                                            .addGroup(jpAddPatientLayout.createSequentialGroup()
                                                .addGroup(jpAddPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jpAddPatientLayout.createSequentialGroup()
                                                        .addComponent(jLabel60, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(10, 10, 10)
                                                        .addGroup(jpAddPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(txtPulse, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(ind16, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                    .addGroup(jpAddPatientLayout.createSequentialGroup()
                                                        .addComponent(jLabel79, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(10, 10, 10)
                                                        .addGroup(jpAddPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(txtPno, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(ind19, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                .addGap(127, 127, 127)))
                                        .addGroup(jpAddPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(jpAddPatientLayout.createSequentialGroup()
                                                .addComponent(jLabel61)
                                                .addGap(4, 4, 4)
                                                .addComponent(txtPDr, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jpAddPatientLayout.createSequentialGroup()
                                                .addComponent(jScrollPane1)
                                                .addGap(1, 1, 1)))))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpAddPatientLayout.createSequentialGroup()
                        .addComponent(jLabel39)
                        .addGap(254, 254, 254))))
        );
        jpAddPatientLayout.setVerticalGroup(
            jpAddPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpAddPatientLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jpAddPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jpAddPatientLayout.createSequentialGroup()
                        .addComponent(jLabel39)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpAddPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpAddPatientLayout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jLabel54))
                            .addGroup(jpAddPatientLayout.createSequentialGroup()
                                .addComponent(txtPname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(ind13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jpAddPatientLayout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(jLabel58))))
                    .addGroup(jpAddPatientLayout.createSequentialGroup()
                        .addComponent(cbPGenderr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(ind20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)))
                .addGap(17, 17, 17)
                .addGroup(jpAddPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpAddPatientLayout.createSequentialGroup()
                        .addGroup(jpAddPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel53)
                            .addComponent(txtPWeghit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jpAddPatientLayout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(jLabel57)))
                        .addGap(3, 3, 3)
                        .addComponent(ind12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpAddPatientLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(cbPBloodr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(ind21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(15, 15, 15)
                .addGroup(jpAddPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpAddPatientLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel52))
                    .addGroup(jpAddPatientLayout.createSequentialGroup()
                        .addComponent(txtPRoom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(ind14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpAddPatientLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel55))
                    .addGroup(jpAddPatientLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(txtPAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(1, 1, 1)
                .addComponent(ind10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(jpAddPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpAddPatientLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel59))
                    .addGroup(jpAddPatientLayout.createSequentialGroup()
                        .addComponent(txtPBT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(ind15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpAddPatientLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(jpAddPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel56)
                            .addComponent(txtPDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(1, 1, 1)
                .addComponent(ind9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(jpAddPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpAddPatientLayout.createSequentialGroup()
                        .addComponent(txtPulse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(ind16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpAddPatientLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(jpAddPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel60)
                            .addComponent(jLabel61)
                            .addComponent(txtPDr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addComponent(ind11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(jpAddPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpAddPatientLayout.createSequentialGroup()
                        .addGroup(jpAddPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpAddPatientLayout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jLabel62))
                            .addGroup(jpAddPatientLayout.createSequentialGroup()
                                .addGroup(jpAddPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtPRT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel64))
                                .addGap(0, 0, 0)
                                .addComponent(ind17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(11, 11, 11)
                        .addGroup(jpAddPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpAddPatientLayout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jLabel63))
                            .addGroup(jpAddPatientLayout.createSequentialGroup()
                                .addComponent(txtPBP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(ind18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jpAddPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpAddPatientLayout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jLabel79))
                            .addGroup(jpAddPatientLayout.createSequentialGroup()
                                .addComponent(txtPno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(ind19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                        .addComponent(btnAddPatient, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jpAddPatient, javax.swing.GroupLayout.DEFAULT_SIZE, 793, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpAddPatient, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddPatientMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddPatientMouseClicked
        // TODO add your handling code here:
        try {
            int result = 0;
            String pname = this.txtPname.getText();
            String page = this.txtPAge.getText();
            String pweghit = this.txtPWeghit.getText();
            String proom = this.txtPRoom.getText();
            String pbodyt = this.txtPBT.getText();
            String pulse = this.txtPulse.getText();
            String prt = this.txtPRT.getText();
            String pbp = this.txtPBP.getText();
            String pdate = this.txtPDate.getText();
            String pdr = this.txtPDr.getText();
            String pnote = this.txtPNote.getText();
            String phone = this.txtPno.getText();
            String pgender = this.cbPGenderr.getText();
            String pblood = this.cbPBloodr.getText();
            String ac = "Active";
            

            
            addpat = con.prepareStatement(
                " insert into patient (Name,Gender,BloodGroup,Age,"
                + "Weghit,RoomNumber,BodyT,PulseRate,ResT,BloodPressure,Date,Status,Doctor,Notes,phone)"
                + " values (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)"
            );

            addpat.setString(1, pname);
            addpat.setString(2, pgender);
            addpat.setString(3, pblood);
            addpat.setString(4, page);
            addpat.setString(5, pweghit);
            addpat.setString(6, proom);
            addpat.setString(7, pbodyt);
            addpat.setString(8, pulse);
            addpat.setString(9, prt);
            addpat.setString(10, pbp);
            addpat.setString(11, pdate);
            addpat.setString(12, ac);
            addpat.setString(13, pdr);
            addpat.setString(14, pnote);
            addpat.setString(15, phone);

            result = addpat.executeUpdate();
            addpat.close();
            pa();
            PaClear();
            sql.close();

        } catch (SQLException s) {
            JOptionPane.showMessageDialog(null, "Make sure that you entered all the fields");
            s.printStackTrace();
        }
    }//GEN-LAST:event_btnAddPatientMouseClicked
 private void PaClear() {
        String s = "";
        txtPname.setText(s);
        txtPAge.setText(s);
        txtPWeghit.setText(s);
        txtPRoom.setText(s);
        txtPBT.setText(s);
        txtPulse.setText(s);
        txtPRT.setText(s);
        txtPBP.setText(s);
        txtPDate.setText(s);
        txtPDr.setText(s);
        txtPNote.setText(s);
        cbPBloodr.setText(s);
        cbPGenderr.setText(s);
       
    }
 public void pa() {
        try {
            sql = con.createStatement();
            rs = sql.executeQuery(
                    "select CardNumber,Name from patient "
                    + "where Name= " + "'" + txtPname.getText() + "'");
            while (rs.next()) {
                String ID = rs.getString("CardNumber");
                JOptionPane.showMessageDialog(null, "Patient Successfully Added! With Card number " + ID);

            }
        } catch (SQLException e) {
            e.printStackTrace();
        }

    }
    private void btnAddPatientMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddPatientMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddPatientMouseEntered

    private void txtPnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPnameActionPerformed

    private void txtPBPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPBPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPBPActionPerformed

    private void txtPnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPnoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Refree.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Refree.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Refree.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Refree.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Refree().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnAddPatient;
    public javax.swing.JTextField cbPBloodr;
    public javax.swing.JTextField cbPGenderr;
    private javax.swing.JPanel ind10;
    private javax.swing.JPanel ind11;
    private javax.swing.JPanel ind12;
    private javax.swing.JPanel ind13;
    private javax.swing.JPanel ind14;
    private javax.swing.JPanel ind15;
    private javax.swing.JPanel ind16;
    private javax.swing.JPanel ind17;
    private javax.swing.JPanel ind18;
    private javax.swing.JPanel ind19;
    private javax.swing.JPanel ind20;
    private javax.swing.JPanel ind21;
    private javax.swing.JPanel ind9;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel jpAddPatient;
    public javax.swing.JTextField txtPAge;
    public javax.swing.JTextField txtPBP;
    public javax.swing.JTextField txtPBT;
    public javax.swing.JTextField txtPDate;
    public javax.swing.JTextField txtPDr;
    public javax.swing.JTextArea txtPNote;
    public javax.swing.JTextField txtPRT;
    public javax.swing.JTextField txtPRoom;
    public javax.swing.JTextField txtPWeghit;
    public javax.swing.JTextField txtPname;
    public javax.swing.JTextField txtPno;
    public javax.swing.JTextField txtPulse;
    // End of variables declaration//GEN-END:variables
}
